language: scala
sudo: false
before_install: umask 0022
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
scala:
  - 2.11.8
  - 2.10.6
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

script: sbt ++$TRAVIS_SCALA_VERSION test
